### ISSUE TITLE
Remove `compare-versions` package and logic

### ISSUE THREAD

**Issue by lteacher** [lteacher/lambda-chain#6]
There is a package used called `compare-versions`.

It is imported [currently in this location](https://github.com/lteacher/lambda-chain/blob/87e0bc1223e1bfd7041f414ce8a2304f5bca71c2/lib/handler-factory.js#L4-L6) and it is used [over here](https://github.com/lteacher/lambda-chain/blob/87e0bc1223e1bfd7041f414ce8a2304f5bca71c2/lib/handler-factory.js#L23-L28)

Its not really necessary and means that an extra dependency is required which I would like to minimise since everything is going to be packaged up and push to AWS if the package is ever used.

This card is to remove this logic, as well as the [dependency from the package.json found here](https://github.com/lteacher/lambda-chain/blob/87e0bc1223e1bfd7041f414ce8a2304f5bca71c2/package.json#L27)

An additional challenge is to **adjust the test** which will fail once this logic is removed.

The logic using this package can just be remove in the condition and left with the else check as the only evaluated check.

**Comment by nab911** [comment]
I'll take a crack at this for Hacktoberfest!

**Comment by lteacher** [comment]
Sure thing :)
